

--Get All Expense
SELECT 	CONCAT(STRFTIME('%Y',CREATED_DATE),STRFTIME('%M',CREATED_DATE)) AS DATE,
	    CONCAT(UPPER(SUBSTRING(C.CATEGORY_NAME,1,1)),LOWER(SUBSTRING(C.CATEGORY_NAME,2,LENGTH(C.CATEGORY_NAME)))) AS CATEGORY_NAME,
		E.ITEM AS ITEM,
		PRINTF('$%.2F',E.AMOUNT) AS AMOUNT,
		E.EXPENSE_ID AS EXPENSE_ID
		FROM EX_EXPENSE AS E 
		JOIN EX_CATEGORY AS C ON E.CATEGORY_ID=C.CATEGORY_ID 
		WHERE E.USER_ID=8 AND DATE='202412'
		ORDER BY E.CREATED_DATE;
		
		